version: '3.8'

services:

  # -----------------------------
  #           KAFKA (KRaft)
  # -----------------------------
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'nUlcKC7PSvGm1i2gHyAqEg'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /tmp/kraft-logs
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  # -----------------------------
  #       SCHEMA REGISTRY
  # -----------------------------
  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.3
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8082:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  # -----------------------------
  #          ksqlDB Server
  # -----------------------------
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.29.0
    container_name: ksqldb-server
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET: earliest
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/info || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s


  # -----------------------------
  #         INIT SCRIPTS
  # -----------------------------
  kafka-init:
    build:
      context: . 
      dockerfile_inline: |
        FROM python:3.12-slim
        WORKDIR /app
        COPY requirements-init.txt .
        RUN pip install --no-cache-dir -r requirements-init.txt
        COPY create_topic.py register_schema.py init_all.py ./
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    volumes:
      - ./event_normalized.avsc:/schemas/event_normalized.avsc:ro
    networks:
      - kafka-net
    command: ["python", "init_all.py"]
    restart: "no"

  # -----------------------------
  #          PRODUCERS
  # -----------------------------
  kafka-producer:
    build: ./kafka-producer
    container_name: kafka-producer
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    networks:
      - kafka-net

  kafka-producer2:
    build: ./kafka-producer2
    container_name: kafka-producer2
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    networks:
      - kafka-net

  # -----------------------------
  #           KSQL CLI
  # -----------------------------
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.29.0
    container_name: ksqldb-cli
    depends_on:
      ksqldb-server:
        condition: service_healthy
    entrypoint: /bin/sh
    tty: true
    networks:
      - kafka-net

  # -----------------------------
  #        SPARK CONSUMER
  # -----------------------------
  spark-consumer:
    build: ./spark-consumer
    container_name: spark-consumer
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    networks:
      - kafka-net
    environment:
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
    volumes:
      - ./spark-consumer/events_output:/app/events_output

volumes:
  kafka_data:

networks:
  kafka-net:
    driver: bridge
